# Generated by Django 5.0.1 on 2024-04-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='document'),
        ),
    ]
