# Generated by Django 5.0.1 on 2024-04-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='docfile',
        ),
    ]
